[project]
name = "decodex01"
version = "0.1.0"
description = "Local code intelligence engine"
authors = [
    { name = "hazalkoom" }
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pybind11>=2.11.0",
    "sqlalchemy (>=2.0.51,<3.0.0)"
]

[build-system]
requires = ["scikit-build-core", "pybind11"]
build-backend = "scikit_build_core.build"

[tool.scikit-build]
build-dir = "build/{wheel_tag}"
editable.rebuild = true
editable.verbose = true
[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)",
    "scikit-build-core>=0.10.0",
    "hypothesis (>=6.156.4,<7.0.0)",
    "pytest-benchmark (>=5.2.3,<6.0.0)",
    "pytest-cov (>=7.1.0,<8.0.0)",
    "gcovr (>=8.6,<9.0)"
]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.mutmut]
paths_to_mutate = "src/"
tests_dir = "tests/"
runner = "python -m pytest -x --benchmark-disable"
